services:
  app.controller.indikator:
    class: AppBundle\Controller\IndikatorController
    arguments: [@service_container, @app.form.indikator, @app.entity.indikator]

  app.controller.user:
    class: AppBundle\Controller\UserController
    arguments: [@service_container, @app.form.user, @app.entity.user]

  app.controller.propinsi:
    class: AppBundle\Controller\PropinsiController
    arguments: [@service_container, @app.form.propinsi, @app.entity.wilayah]

  app.controller.kabupaten:
    class: AppBundle\Controller\KabupatenController
    arguments: [@service_container, @app.form.kabupaten, @app.entity.wilayah]

  app.controller.kecamatan:
    class: AppBundle\Controller\KecamatanController
    arguments: [@service_container, @app.form.kecamatan, @app.entity.wilayah]

  app.controller.kelurahan:
    class: AppBundle\Controller\KelurahanController
    arguments: [@service_container, @app.form.kelurahan, @app.entity.wilayah]

  app.controller.block:
    class: AppBundle\Controller\BlockController
    arguments: [@service_container, @app.form.block, @app.entity.block]