services:
  app.entity.indikator:
    class: AppBundle\Entity\Indikator

  app.entity.user:
    class: AppBundle\Entity\User

  app.entity.wilayah:
    class: AppBundle\Entity\Wilayah

  app.entity.block:
    class: AppBundle\Entity\Block