services:
  app.form.indikator:
    class: AppBundle\Form\IndikatorType
    arguments: [@males.guesser]

  app.form.user:
     class: AppBundle\Form\UserType
     arguments: [@males.guesser, %security.role_hierarchy.roles%]

  app.form.propinsi:
     class: AppBundle\Form\PropinsiType
     arguments: [@males.guesser]

  app.form.kabupaten:
     class: AppBundle\Form\KabupatenType
     arguments: [@males.guesser, @doctrine.orm.entity_manager]

  app.form.kabupaten_type:
     class: AppBundle\Form\KabupatenWithTransformerType
     arguments: [@doctrine.orm.entity_manager]
     tags:
      - { name: form.type, alias: kabupaten }

  app.form.kecamatan_type:
     class: AppBundle\Form\KecamatanWithTransformerType
     arguments: [@doctrine.orm.entity_manager]
     tags:
      - { name: form.type, alias: kecamatan }

  app.form.kecamatan:
     class: AppBundle\Form\KecamatanType
     arguments: [@males.guesser, @doctrine.orm.entity_manager]

  app.form.kelurahan:
     class: AppBundle\Form\KelurahanType
     arguments: [@males.guesser, @doctrine.orm.entity_manager]