home_dashboard:
    path:     /admin/demo/dashboard/
    methods:  [GET]
    defaults: { _controller: AppBundle:Demo:dashboard }

query_dashboard:
    path:     /admin/demo/query/
    methods:  [GET]
    defaults: { _controller: AppBundle:Demo:query }

report_dashboard:
    path:     /admin/demo/report/
    methods:  [POST]
    defaults: { _controller: AppBundle:Demo:report }